services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - ai-pasala-net

  api-gateway:
    build: ./api-gateway
    volumes:
      - ./api-gateway:/app
      # - /app/node_modules
    ports:
      - "4000:4000"
    networks:
      - ai-pasala-net
    depends_on:
      - agents
      - translate
      # - sahana-translate
      - mongo
      - redis

  agents:
    build: ./agents
    volumes:
      - ./agents:/app
    ports:
      - "5000:5000"
    networks:
      - ai-pasala-net
    environment:
      OLLAMA_API_URL: "http://ollama:11434"
    depends_on:
      - ollama
      - mongo
      - redis
      - chromadb

  translate:
    build: ./translator
    ports:
      - "5010:5010"
    networks:
      - ai-pasala-net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

  # sahana-translate:
  #   build: ./sahana-translate
  #   ports:
  #     - "5011:5011"
  #   networks:
  #     - ai-pasala-net
  #   depends_on:
  #     - mlflow

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - ai-pasala-net
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia

  # mlflow:
  #   image: mlflow/mlflow:latest
  #   environment:
  #     MLFLOW_TRACKING_URI: sqlite:///mlflow.db
  #   volumes:
  #     - ./mlruns:/mlflow/mlruns
  #     - ./mlflow.db:/mlflow/mlflow.db
  #   ports:
  #     - "5040:5000"
  #   networks:
  #     - ai-pasala-net

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - ai-pasala-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - ai-pasala-net

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "5050:8000"
    networks:
      - ai-pasala-net

volumes:
  mongo-data:
  ollama-data:

networks:
  ai-pasala-net:
    driver: bridge
