FROM python:3.12.3-slim

# Set work directory
WORKDIR /app

# Install system deps
RUN apt-get update && apt-get install -y build-essential curl

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install watchdog

# Copy app code
COPY ./app ./app

# Expose port
EXPOSE 5000

# Start the FastAPI server
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
